#!/bin/sh
set -e -u

########## CONFIGURATION - You may want to change these ########################

# Optional: Preprocessor flags ("-DADAPTER_DEBUG_MODE" enables debug messages)
PRECICE_BUILD_FLAGS="-DADAPTER_DEBUG_MODE"

# Build command and options
# In order to compile with multiple threads, add e.g. "-j 4".
# Make sure that these options are supported by your OpenFOAM version.
adapter_build_command(){
    wmake libso
}

# Where should the adapter be built? Default: "${FOAM_USER_LIBBIN}"
FOAM_LIBBIN="${FOAM_USER_LIBBIN:-}"

# More information for compatibility with OpenFOAM
DOC_COMPATIBILITY="https://www.precice.org/adapter-openfoam-support.html"

################################################################################
# Funtion to print to screen and copy to a logfile
log() {
    echo "$@" | tee -a "Allwmake.log"
}
################################################################################

# Information header
log "Building the OpenFOAM-preCICE adapter..."
# Check if an OpenFOAM environment is available
log ""
log "Current OpenFOAM environment:"
log "  WM_PROJECT = ${WM_PROJECT:-}"
log "  WM_PROJECT_VERSION = ${WM_PROJECT_VERSION:-}"

if [ -z "${WM_PROJECT:-}" ]; then
    log ""
    log "=== ERROR: It looks like no OpenFOAM environment is available. ==="
    log "Possible reasons:"
    log "- Have you loaded the OpenFOAM etc/bashrc file?"
    log "- Are you using a compatible OpenFOAM version?"
    log "  See ${DOC_COMPATIBILITY}"
    exit 1
fi
# Check if this is a compatible OpenFOAM environment
# For now, only check if it is not foam-extend, the main incompatible variant.
if [ "${WM_PROJECT:-}" = "foam" ]; then
    log ""
    log "=== ERROR: foam-extend is not compatible with the adapter."
    log "Make sure you are using a compatible OpenFOAM version:"
    log "  ${DOC_COMPATIBILITY}"
    exit 1
fi

if [ -z "${PRECICE_PREFIX:-}" ]; then
    log ""
    log "=== WARNING: It looks like PRECICE_PREFIX specified. ==="
    export PRECICE_PREFIX = "/usr/lib/"
    log ""
    log "Will proceed with default locaton $PRECICE_PREFIX"
    log "See also ${DOC_COMPATIBILITY}"
fi

log ""
log "The adapter will be built into ${FOAM_LIBBIN}"
log "preCICE prefix dir ${PRECICE_PREFIX}"
log "preCICE build flags ${PRECICE_BUILD_FLAGS}"

# Run wmake (build the adapter) and check the exit code
log ""
log "Building with WMake (see the wmake.log log file)...\n"
if ! adapter_build_command 2>&1 | tee wmake.log ||
    [ "$(grep -c -E "error:" wmake.log)" -ne 0 ]; then
    log "=== ERROR: Building failed. See wmake.log for more. ==="
    log "Possible causes:"
    log "- Make sure you are using a compatible version of the adapter for your OpenFOAM version:"
    log "  ${DOC_COMPATIBILITY}"
    log "- Is preCICE discoverable at compile time? Check the content of ADAPTER_PKG_CONFIG_CFLAGS above."
    exit 1
else
    ADAPTER_WMAKE_UNDEFINED_SYMBOLS=$(grep -c -E "undefined|not defined" wmake.log) || echo "Everything looks fine in wmake.log."
    ldd -r "${FOAM_LIBBIN}/libpreciceAdapterFunctionObject.so" >ldd.log 2>&1
    ADAPTER_LD_UNDEFINED_SYMBOLS=$(grep -c -E "undefined|not defined" ldd.log) || echo "Everything looks fine in ldd.log."
    if [ "${ADAPTER_WMAKE_UNDEFINED_SYMBOLS}" -gt 0 ] || [ "${ADAPTER_LD_UNDEFINED_SYMBOLS}" -gt 0 ]; then
        log "=== ERROR: Building completed with linking problems: there were undefined symbols. ==="
        log "Possible causes:"
        log "- Is preCICE discoverable at runtime?"
        log "- Create symbolic links to preCICE libraries with ln -s \$PRECICE_PREFIX/lib/libprecice.so.2 /usr/lib/libprecice.so.2"
        log "See wmake.log and ldd.log for more details."
    else
        log "=== OK: Building completed successfully! ==="
    fi
fi
