#!/bin/bash

# Solid participant

# Run this script in one terminal and the "runThermo" script in another terminal.
# These scripts present how the two participants would be started manually.
# Alternatively, you may execute the "Allrun" script in one terminal.

# The script "Allclean" cleans-up the result and log files.

# Prepare
blockMesh -case solidDisplacementFoam

# Run
solidDisplacementFoam -case solidDisplacementFoam
